version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - /home/aalannys/data/db:/var/lib/mysql/data
      - /home/aalannys/data/db/logs:/var/lib/mysql/logs
    restart: "always"
    networks:
      - awesomenet

networks:
  awesomenet: