version: "3.7"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    restart: "always"
    networks:
     - awesomenet
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: "always"
    networks:
      - awesomenet

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    restart: "always"
    depends_on:
      - wordpress
    networks:
     - awesomenet

networks:
  awesomenet:
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aalannys/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aalannys/data/wp