#!/bin/bash

mysql << EOF
CREATE DATABASE wordpress;
DROP USER IF EXISTS '$USER'@'%';
CREATE USER '$USER'@'%' IDENTIFIED BY '$USERPSWD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$USER'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$ROOTPSWD';
EOF
