#!/bin/sh

mysql << EOF
CREATE DATABASE wordpress;
DROP USER IF EXISTS '$USER'@'localhost';
CREATE USER '$USER'@'%' IDENTIFIED BY '$USERPSWD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$USER'@'localhost';
FLUSH PRIVILEGES;
ALTER USER 'root'@'%' IDENTIFIED BY '$ROOTPSWD';
EOF
